/**
 * @file array_arena_cfg.h
 * @brief Configuration of the initial lengths of the free lists within the
 *        array arena.
 *
 * @note This file can be generated by the scripts/discretize_arena.py script
 *       (manually run) or it can be manually modified as the user wishes.
 *
 * @date Sat, Jul 05, 2025 :: 09:50:50 AM 
 * @copyright MIT License
 */

#ifndef _ARRAY_CFG_H_
#define _ARRAY_CFG_H_

// Given the arena size: 15000 bytes, discretize_python.py allocates the bytes
// as shown below:

#define BLOCKS_1024_LIST_INIT_LEN   3 // 3072 bytes
#define BLOCKS_512_LIST_INIT_LEN    6 // 3072 bytes
#define BLOCKS_256_LIST_INIT_LEN   12 // 3072 bytes
#define BLOCKS_128_LIST_INIT_LEN   25 // 3200 bytes
#define BLOCKS_64_LIST_INIT_LEN    36 // 2304 bytes
#define BLOCKS_32_LIST_INIT_LEN     8 // 256 bytes
//                                       24 byte gap


#endif // _ARRAY_CFG_H_

